name: Build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: 'pip'

    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    - name: Generate images
      run: |
        git pull
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDE_FORKED_REPOS: true

    - name: Commit stats images
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m 'Update stats images' || true
        git push --force

  activity:
    needs: stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cheesits456/github-activity-readme@16bd144b812ce901e0693fee5c36c02e75e6b4a7
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
